# Generated by Django 4.2.6 on 2023-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
