# Generated by Django 4.2.6 on 2023-11-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
